#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CBIInventoryAPI/CBIInventoryAPI.csproj", "CBIInventoryAPI/"]
COPY ["Business/Business.csproj", "Business/"]
COPY ["DataAccess/DataAccess.csproj", "DataAccess/"]
COPY ["Entities/Entities.csproj", "Entities/"]
COPY ["Core/Core.csproj", "Core/"]
RUN dotnet restore "CBIInventoryAPI/CBIInventoryAPI.csproj"
COPY . .
WORKDIR "/src/CBIInventoryAPI"
RUN dotnet build "CBIInventoryAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CBIInventoryAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CBIInventoryAPI.dll"]